// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Thu Feb 22 18:50:31 2024

ColendaArchitecture ColendaArchitecture_inst
(
	.clk_50(clk_50_sig) ,	// input  clk_50_sig
	.reset(reset_sig) ,	// input  reset_sig
	.dataA(dataA_sig) ,	// input [31:0] dataA_sig
	.dataB(dataB_sig) ,	// input [31:0] dataB_sig
	.out_screen(out_screen_sig) ,	// input  out_screen_sig
	.wrreg_export(wrreg_export_sig) ,	// input  wrreg_export_sig
	.reset_pulsecounter(reset_pulsecounter_sig) ,	// input  reset_pulsecounter_sig
	.wrfull_export(wrfull_export_sig) ,	// output  wrfull_export_sig
	.out_hsync(out_hsync_sig) ,	// output  out_hsync_sig
	.out_vsync(out_vsync_sig) ,	// output  out_vsync_sig
	.B(B_sig) ,	// output [2:0] B_sig
	.G(G_sig) ,	// output [2:0] G_sig
	.R(R_sig) 	// output [2:0] R_sig
);

